### ISSUE TITLE
Refactor components

### ISSUE THREAD

**Issue by ecumene** [SoheilNK/Backgammon#1]
```ts
type Color = "White" | "Black";

type CheckerProps = {
  clr: Color;
};
```

- [x] Change `string` to `Color`
- [x] Change the name of the type for your props to `[ComponentName]Props`
- [x] Export `Color` as a type
- [x] Create a new component named `Board.tsx`
- [x] Import `Color` from `Game.tsx` into `Board.tsx`
- [x] Move Board, Checker, Point into `Board.tsx`
- [x] Import Board from `Board.tsx` from `Game.tsx`
- [x] Pass `initialState` as a prop from `Game.tsx` to `Board.tsx`

**Comment by SoheilNK** [comment]
Hey Mitch, this part is done.
