### ISSUE TITLE
Add state to the game component, pass it down via props

### ISSUE THREAD

**Issue by ecumene** [SoheilNK/Backgammon#5]
![image](https://user-images.githubusercontent.com/6249465/224578597-bfa1f52e-159f-4ff2-8553-5142d0887682.png)

State to add (`useState`): 
 - [x] Current Player ([enum](https://www.typescriptlang.org/docs/handbook/enums.html), or a number) 
 - [x] Current dice roll (two random ###)
 - [x] Board state (string[][])
 - [x] Player won (boolean)

**Comment by SoheilNK** [comment]
done
