### ISSUE TITLE
Implement game rules

### ISSUE THREAD

**Issue by ecumene** [SoheilNK/Backgammon#6]
Once dice rolling is finished, we want to pass the game state to the board component and create a function to determine what to display to the user as input.

Example: After a dice roll, the player is prompted to move their checkers. We shouldn't allow them to move it just anywhere though. Create a custom typescript function to determine based on: 
 - Current player
 - Current board state
 - Current dice roll
 
RETURN:
 - Allowed columns

**Comment by SoheilNK** [comment]
Done
