### ISSUE TITLE
Implement a player indicator

### ISSUE THREAD

**Issue by ecumene** [SoheilNK/Backgammon#9]
- As make your move, the current player should change
 - Begin as white or black, after move is made the player should switch

**Comment by SoheilNK** [comment]
done in board.tsx
//check if player can move again
    if (newDiceRoll[0] == 0 && newDiceRoll[1] == 0) {
      console.log("player can't move again");
      if (currentPlayer == PlayerNames.white) {
        currentPlayer = PlayerNames.black;
      } else {
        currentPlayer = PlayerNames.white;
      }
      
    }
